[project]
name = "yeahtube"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "alembic>=1.17.2",
    "fastapi[standard]>=0.124.4",
    "psycopg2>=2.9.11",
    "sqlalchemy>=2.0.44",
]
